Program 0x8E
Party NO_FRIEND
Bgm Default Default
AreaSettings 0 -1
	SetProgressFlag 0x850
	SetUnk05 0x2
	SetEvent "319" Type 2
	SetJump Type 2 World TT Area 0 Entrance 0 LocalSet 52 FadeType 1
	SetPartyMenu 0

Program 0x8B
Party NO_FRIEND
Bgm Default Default
AreaSettings 0 -1
	SetProgressFlag 0x839
	SetUnk05 0x2
	SetEvent "211" Type 2
	SetJump Type 1 World HB Area 26 Entrance 33 LocalSet 0 FadeType 1
	SetPartyMenu 0
