Program 0x02
Party DEFAULT
Bgm 95 95
AreaSettings 0 -1
	SetProgressFlag 0x4811
	SetEvent "113" Type 2
	SetJump Type 2 World EH Area 0 Entrance 0 LocalSet 56 FadeType 1
	SetPartyMenu 0

Program 0x39
Bgm 185 185
Layout "file/%s/b_ex140.2ld"
AreaSettings 16 -1
	SetProgressFlag 0x481A
	SetUnk05 0x3
	SetEvent "114" Type 18
	SetJump Type 1 World EH Area 15 Entrance 50 LocalSet 0 FadeType 1
	SetInventory 527
	SetPartyMenu 0
